### ISSUE TITLE
squote and dquote remove quotes 

### ISSUE THREAD

**Issue by aslafy-z** [openuado/niet#46] opened 2019-07-26 15:15 UTC
When using squote or dquote mode on a already quoted value, the quotes are dropped (single or doubles).

```
$ echo '{"key": "value"}' | niet key
"key"
$ echo '{"key": "value"}' | niet -f squote key
key
$ echo '{"key": "value"}' | niet -f dquote key
key
```

**Comment by 4383** [comment] 2019-07-26 15:30
Hey there

First thanks to open this issue.

Which version of `niet` you used? (`niet -v`)

I can't reproduce your issue with the `1.5.1`, everything works fine:
```shell
$ echo '{"key": "value"}' | niet -f dquote key
"value"
$ echo '{"key": "value"}' | niet -f squote key
'value'
$ echo '{"key": "value"}' | niet key
value
```

Can you try to update your version if needed:
```shell
python3 -m pip install --user -U niet
```

**Comment by aslafy-z** [comment] 2019-07-27 11:11
I see, I tried using python 2.7 and niet 1.5.1.
In that case, the default behavior seams to be returning value with double quotes.

Reproduction steps:
```
New instance on https://labs.play-with-docker.com/
$ apk add python
$ python -m ensurepip
$ pip install niet
$ echo '{"key": "value"}' | niet key
"value"
```

**Comment by 4383** [comment] 2019-07-27 11:37
Sorry I can't reproduce your issue... everything work fine on my side and like as expected...

Setup my testing env:
```shell
$ cd /tmp
$ mkdir niet
$ cd niet 
$ pipenv shell --two
Creating a virtualenv for this project…
Pipfile: /tmp/niet2/Pipfile
Using /usr/bin/python2 (2.7.15) to create virtualenv…
⠦ Creating virtual environment...Already using interpreter /usr/bin/python2
  No LICENSE.txt / LICENSE found in source
New python executable in ~/.local/share/virtualenvs/niet2-ksYdqxxc/bin/python2
Also creating executable in ~/.local/share/virtualenvs/niet2-ksYdqxxc/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/bin/python2

✔ Successfully created virtual environment! 
Virtualenv location: ~/.local/share/virtualenvs/niet2-ksYdqxxc
Creating a Pipfile for this project…
Launching subshell in virtual environment…
 . /~/.local/share/virtualenvs/niet2-ksYdqxxc/bin/activate
$ pip install niet
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting niet
  Using cached https://files.pythonhosted.org/packages/cf/41/7ab8c109bd8bdb3eee5ab6c41c327c21a6e8842769b4f8a351edac46df3d/niet-1.5.1-py2.py3-none-any.whl
Collecting jmespath==0.9.4 (from niet)
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting future==0.17.1 (from niet)
Collecting PyYAML==5.1 (from niet)
Installing collected packages: jmespath, future, PyYAML, niet
Successfully installed PyYAML-5.1 future-0.17.1 jmespath-0.9.4 niet-1.5.1
```
Then testing niet:
```shell
$ echo '{"key": "value"}' | niet key
value
$  echo '{"key": "value"}' | niet -f dquote key 
"value"
$ echo '{"key": "value"}' | niet -f squote key
'value'
```

Everything work fine even with python 2.7.

Please confirm which version of niet is in use in your env?

**Comment by aslafy-z** [comment] 2019-08-08 17:11
See the repro steps here: https://github.com/openuado/niet/issues/46#issuecomment-515676168

python 2.7.16 & niet 1.5.1
alpine linux 3.10
bash 5.0.0

**Comment by 4383** [comment] 2019-08-08 17:15
@aslafy-z thanks.

I'll try to spend some time to investigate under an alpine environment but everything seems to work like expected on my side for the moment.

Anyway thanks for your feedback :)

**Comment by dj4ngo** [comment] 2019-10-09 20:21
Cannot reproduce it too even on alpine. Are you still facing this issue with latest version of niet ?

**Comment by 4383** [comment] 2022-09-08 07:06
No feedback from the reporter since more than 3 years, I'm closing this issue.

**Closed by 4383** 2022-09-08 07:06 UTC
